components:
- ALICE
- ATLAS
- CMS
- LHCb
- UI
- access
- base
- deposit
- docker
- docs
- fixtures
- global
- glossary
- installation
- kwalitee
- records
- search
- templates
- tests
- travis
- alpaca
