# -*- coding: utf-8 -*-
#
# This file is part of CERN Analysis Preservation Framework.
# Copyright (C) 2016, 2017 CERN.
#
# CERN Analysis Preservation Framework is free software; you can redistribute
# it and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# CERN Analysis Preservation Framework is distributed in the hope that it will
# be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with CERN Analysis Preservation Framework; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.
#
# In applying this license, CERN does not
# waive the privileges and immunities granted to it by virtue of its status
# as an Intergovernmental Organization or submit itself to any jurisdiction.

version: '2.1'
services:
  app:
    build: .
    env_file:
      - cap.env
  redis:
    image: redis
    ports:
      - "6379:6379"
  postgresql:
    image: postgres
    environment:
      - POSTGRES_DB=cap
      - POSTGRES_USER=cap
      - POSTGRES_PASSWORD=cap
    ports:
      - "5432:5432"
  elasticsearch:
    build: ./docker/elasticsearch/
    ports:
      - "9200:9200"
      - "9300:9300"
  rabbitmq:
    image: rabbitmq
    restart: "always"
    ports:
      - "4369:4369"
      - "5672:5672"
  redis-commander:
    image: rediscommander/redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8081:8081
  wdb:
    image: kozea/wdb-server
    ports:
      - 1984:1984
      - 19840:19840
  flower:
    restart: "always"
    build:
      context: .
      args:
        DEBUG: "True"
    command: 'flower -A cap.celery --port=5555'
    ports:
      - "49555:5555"